blank_issues_enabled: false
contact_links:
  - name: 讨论区
    url: https://github.com/denglihong2007/CRSim/discussions/
    about: 使用中若遇到问题或有新点子新需求，请先在这里求助和征求意见。
  - name: 问题反馈
    url: https://github.com/denglihong2007/CRSim/issues
    about: 若你发现了应用的问题，请在这里反馈。
